[workspace]
members = [
    "crates/threshold-template", "crates/threshold-client",
    "crates/threshold-poc-core",
    "crates/threshold-exchange-template",
    "crates/threshold-audit-template",
    "crates/threshold-infrastructure-template",
    "crates/threshold-grant-template",
    "crates/threshold-community-template",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
