import { readFile, readdir } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const output = resolve(dirname(fileURLToPath(import.meta.url)), '..', '_site');
const files = (await readdir(output)).sort();
const expected = ['.nojekyll', 'bounties-archive.html', 'bounties.css', 'bounties.html', 'bounties.js', 'bounty-index.json', 'bounty-proof', 'index.html', 'sandbox.js', 'wire.css', 'wire.js'];
if (JSON.stringify(files) !== JSON.stringify(expected)) throw new Error(`Unexpected Pages files: ${files.join(', ')}`);
const html = await readFile(join(output, 'index.html'), 'utf8');
if (!html.includes('id="sandbox-dialog"') || !html.includes('id="flow"')) throw new Error('Map or sandbox missing');
if (/(?:href|src)="\//.test(html)) throw new Error('Root-relative URL breaks project Pages paths');
if (/\/explore|\/showcase|\/observer|\/api\//.test(html)) throw new Error('Extra page or API reference remains');
const script = await readFile(join(output, 'wire.js'), 'utf8');
if (/\bfetch\s*\(/.test(script)) throw new Error('Static map should not query a backend');
const sandbox = await readFile(join(output, 'sandbox.js'), 'utf8');
if (/\bfetch\s*\(/.test(sandbox) || /\bchoices\b|\bplan\b/.test(sandbox)) throw new Error('Sandbox must remain independent of the map and backend');
const bounties = await readFile(join(output, 'bounties.html'), 'utf8');
if (/(?:href|src)="\//.test(bounties)) throw new Error('Bounty board has a root-relative asset');
if (!bounties.includes('id="bounty-list"') || !bounties.includes('ESMERALDA TESTNET')) throw new Error('Bounty board missing');
const bountyScript = await readFile(join(output, 'bounties.js'), 'utf8');
if (!bountyScript.includes('data.verified !== true') || !bountyScript.includes('component.header?.template_address')) throw new Error('Bounty board must check indexer verification and template');
const bountyIndex = JSON.parse(await readFile(join(output, 'bounty-index.json'), 'utf8'));
if (bountyIndex.network !== 'esmeralda' || !Array.isArray(bountyIndex.people) || !Array.isArray(bountyIndex.bounties)) throw new Error('Invalid bounty index');
if (bountyIndex.bounties.length !== 0) throw new Error('Former-chain bounties must not appear on the current board');
const archive = await readFile(join(output, 'bounties-archive.html'), 'utf8');
if (/(?:href|src)="\//.test(archive) || /<script\b|\bfetch\s*\(/i.test(archive)) throw new Error('Archive must render offline with relative assets');
if (!archive.includes('Historical snapshot.') || !archive.includes('Bounties powered by Threshold.') || (archive.match(/class="card"/g) || []).length !== 5) throw new Error('Offline archive is incomplete');
const proofFiles = await readdir(join(output, 'bounty-proof'));
if (proofFiles.filter(file => file.endsWith('-receipt.json')).length !== 19 || !proofFiles.includes('demo-index.json') || !proofFiles.includes('verified-state.json')) throw new Error('Archived proof bundle is incomplete');
console.log('Checked independent sandbox, current bounty board, and offline proof archive');
