[package]
name = "threshold-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tari_crypto = "=0.23.2"
tari_utilities = "=0.10.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.10"
threshold-template = { path = "../threshold-template" }
tari_template_lib = { version = "=0.32.1", features = ["serde"] }
tari_engine_types = "=0.41.2"
tari_ootle_transaction = "=0.41.2"
tari_bor = "=0.16.1"
ootle_byte_type = { version = "=0.13.0", features = ["crypto"] }
tari_ootle_wallet_crypto = { version = "=0.43.0", features = ["serde"] }
ootle-rs = "=0.23.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
hex = "0.4"
minicbor = { version = "=2.3.0", features = ["derive", "std"] }

[features]
engine-tests = ["dep:tari_template_test_tooling"]

[dependencies.tari_template_test_tooling]
version = "=0.41.2"
optional = true
